# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from AICardProto import AICardProto_pb2 as AICardProto_dot_AICardProto__pb2


class GameServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Interact = channel.unary_unary(
                '/AIPokerProto.GameServices/Interact',
                request_serializer=AICardProto_dot_AICardProto__pb2.GameInteraction.SerializeToString,
                response_deserializer=AICardProto_dot_AICardProto__pb2.GameHistory.FromString,
                )
        self.Join = channel.unary_unary(
                '/AIPokerProto.GameServices/Join',
                request_serializer=AICardProto_dot_AICardProto__pb2.PlayerDefinition.SerializeToString,
                response_deserializer=AICardProto_dot_AICardProto__pb2.PlayerInscription.FromString,
                )


class GameServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Interact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Interact': grpc.unary_unary_rpc_method_handler(
                    servicer.Interact,
                    request_deserializer=AICardProto_dot_AICardProto__pb2.GameInteraction.FromString,
                    response_serializer=AICardProto_dot_AICardProto__pb2.GameHistory.SerializeToString,
            ),
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=AICardProto_dot_AICardProto__pb2.PlayerDefinition.FromString,
                    response_serializer=AICardProto_dot_AICardProto__pb2.PlayerInscription.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AIPokerProto.GameServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Interact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AIPokerProto.GameServices/Interact',
            AICardProto_dot_AICardProto__pb2.GameInteraction.SerializeToString,
            AICardProto_dot_AICardProto__pb2.GameHistory.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AIPokerProto.GameServices/Join',
            AICardProto_dot_AICardProto__pb2.PlayerDefinition.SerializeToString,
            AICardProto_dot_AICardProto__pb2.PlayerInscription.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
